### ISSUE TITLE
사용자 정보 오류(members/me, members?githubId)

### ISSUE THREAD

**Issue by posite** [tukcom2023CD/DragonGuard-JinJin#111]
- [x] commits의 수가 매우 작음(아마도 issues 수랑 같은게 아닐까? 의심됨)
- [x] gitRepos가 빈 배열로 옴, 계속 불러도 채워지지 않음(DB에는 git_repo에 들어가 있음)
- [x] 조직 등록 이후 issues, pr, reviews가 null이됨

**Comment by posite** [comment]
오류 수정 완료

**Comment by ohksj77** [comment]
DTO에 값을 잘못 넣었던 단순 구현 오류였습니다.
