### ISSUE TITLE
api 호출도중 기능에서 나가는 경우 api 취소 안되는 오류

### ISSUE THREAD

**Issue by HJ39** [tukcom2023CD/DragonGuard-JinJin#112]
사용자의 변심으로 다른기능 쓰러 화면 전환하는경우 
호출한 API 취소하는 기능

**Comment by ohksj77** [comment]
어떤 의미인지 잘 모르겠는데 설명해주세요
백엔드 API 실행되고 나서는 아마 계속 코드가 돌아갈 것입니다.
